Create database SQLIP;
USE SQLIP;
---------******-RECURSIVE CTE(COMMON TABLE EXPRESSION)-******---------
--Odd number CTE
WITH  mycte AS
(
    SELECT 1 AS n
    UNION ALL
    SELECT n + 2
    FROM mycte
    WHERE n < 5
)

SELECT * FROM mycte;
--Even number
WITH EVENCTE AS
(
SELECT 2 AS EN
UNION ALL
SELECT EN+2 FROM EVENCTE WHERE EN<20
)
SELECT * FROM EVENCTE

--OPTION (MAXRECURSION 0);
CREATE TABLE EMP(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(250) NOT NULL ,
EMAIL VARCHAR(250) NOT NULL,
)
CREATE TABLE STAGEEMP(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(250) NOT NULL ,
EMAIL VARCHAR(250) NOT NULL,
)

INSERT INTO EMP VALUES('Laiba','Laiba@gmail.com'),
('Sophia','SophiaLaiba@gmail.com'),
('Samreen','Samreen@gmail.com'),
('Sandy','Sandy@gmail.com')

MERGE INTO STAGEEMP  AS EMP
USING EMP AS SEMP
ON EMP.EMAIL=SEMP.EMAIL
WHEN MATCHED THEN 
UPDATE SET EMP.NAME=SEMP.NAME,EMP.EMAIL=SEMP.EMAIL
WHEN NOT MATCHED THEN
INSERT (NAME,EMAIL) VALUES (SEMP.NAME,SEMP.EMAIL);


SELECT * FROM EMP
SELECT * FROM STAGEEMP